src/Finance.Control.WebApp/Controllers/RevenuesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Finance.Control.webApp.Controllers
{
    [Authorize]
    public class RevenuesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Finance.Control.WebApp/Views/Shared/_Layout.cshtml
@using Finance.Control.webApp.Common.Libraries
@using StackExchange.Profiling
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] </title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Finance.Control.WebApp.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    <link href="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    @await RenderSectionAsync("Styles", false)
</head>
<body>

    <mini-profiler position="RenderPosition.BottomRight" />

    @if (User.Identity is { IsAuthenticated: true })
    {
        <div id="wrapper" class="toggled d-flex sb-sidenav-toggled">

            <partial name="_Sidebar" />

            <!-- Page content wrapper-->
            <div id="page-content-wrapper">

                <partial name="_Navbar" />

                <div class="container-fluid p-3">
                    @RenderBody()
                </div>

            </div>
        </div>
    }
    else
    {
        @RenderBody()
    }

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 
    <!-- SweetAlert 2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   
    @await RenderSectionAsync("Scripts", false)

    @Html.RenderFlashMessage()
</body>
</html>

src/Finance.Control.WebApp/Views/Shared/_NavBar.cshtml
<div id="navbar-wrapper">
    <nav class="navbar navbar-expand-lg navbar-light navbar-light bg-light">
        <div class="container-fluid">
            <button class="btn" id="sidebarToggle">
                <i class="fa fa-bars"></i>
            </button>

            <div class="navbar-right" action="/account/logoff" method="post">
                <ul class="nav navbar-right">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-black"
                           id="navbarDropdown"
                           href="#"
                           role="button"
                           data-bs-toggle="dropdown"
                           aria-haspopup="true"
                           aria-expanded="false">
                            <i class="fa-solid fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end"
                             aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="account" asp-action="SignOut">
                                <i class="fa fa-sign-out-alt"></i> Logout
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

    </nav>
</div>

src/Finance.Control.WebApp/Views/Shared/_Sidebar.cshtml
<div id="sidebar-wrapper">

    <button class="btn" id="close-sidebar">
        <i class="fas fa-times text-white"></i>
    </button>

    <div class="sidebar-logo">
        <img src="~/images/progressao-grafica.png" />
    </div>

    <nav class="sidebar-nav"> 

        <ul>
            <li>
                <a asp-controller="Home" asp-action="Index" title="Home" class="submenu-link">
                    <i class="fa-solid fa-house"></i>
                    <span>
                        Home Page
                    </span>      
                </a>
            </li>
        </ul>

        <p class="text-white mx-3 span-ocult">Cadastros</p>

        <ul>          
            <li>
                <a asp-controller="AppUser" asp-action="Index" title="Dashboard" class="submenu-link">
                    <i class="fa-solid fa-user"></i>
                    <span>
                        Usuários
                    </span>                 
                </a>
            </li>          

            <li>
                <a asp-controller="Revenues" asp-action="Index" title="Home" class="submenu-link">
                    <i class="fa-solid fa-file-invoice"></i>
                    <span>
                        Transações
                    </span>      
                </a>
            </li>

            <li>
                <a asp-controller="AccountsPayable" asp-action="Index" title="Home" class="submenu-link">
                    <i class="fa-solid fa-file-invoice"></i>
                    <span>
                        Contas a Pagar
                    </span>
                </a>
            </li>

            <li>
                <a asp-controller="Category" asp-action="Index" title="Home" class="submenu-link">
                    <i class="fa-solid fa-file-invoice"></i>
                    <span>
                        Categorias
                    </span>
                </a>
            </li>
        </ul>

    </nav>
</div>